# Generated by Django 4.1.7 on 2023-02-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liste', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadeau',
            name='est_reserve',
            field=models.BooleanField(default=False),
        ),
    ]
