# Generated by Django 4.1.7 on 2023-02-22 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liste', '0003_cadeau_montant_reserve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadeau',
            name='est_reserve',
        ),
    ]
