# Generated by Django 4.1.7 on 2023-02-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_reservation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='montant',
            field=models.FloatField(default=0),
        ),
    ]
